// Generated by scripts/generate_api_types.py. Do not edit.

export type BaselineRequest = {
  "target"?: number;
  "confident"?: boolean;
  "max_p95_ms"?: (number | null);
  "baseline": Record<string, unknown>;
  "max_recall_drop"?: number;
  "max_p95_increase"?: number;
  "min_p95_increase_ms"?: number;
}

export type BaselineResponse = {
  "baseline_label": (string | null);
  "baseline_created_at": (string | null);
  "baseline_index": (string | null);
  "points": Array<PointDeltaOut>;
  "comparable": boolean;
  "regressed": boolean;
  "recall_comparable": boolean;
  "latency_comparable": boolean;
  "notes": Array<string>;
  "baseline_recommended": (number | null);
  "recommended": (number | null);
  "max_recall_drop": number;
  "max_p95_increase": number;
  "min_p95_increase_ms": number;
}

export type CompareCandidateOut = {
  "index": number;
  "name": string;
  "kind": string;
  "ntotal": number;
  "params": Record<string, (number | number | boolean | string)>;
  "search_param": ("nprobe" | "efSearch" | null);
  "max_value": (number | null);
}

export type CompareJobResponse = {
  "job_id": string;
  "status": "running" | "done" | "failed" | "cancelled";
  "progress": number;
  "message": string;
  "error": (string | null);
  "result": (CompareResultOut | null);
}

export type CompareMeasurementOut = {
  "name": string;
  "kind": string;
  "params": Record<string, number>;
  "serialized_bytes": number;
  "recall": number;
  "recall_ci_low": (number | null);
  "recall_ci_high": (number | null);
  "latency_mean_ms": number;
  "latency_p95_ms": number;
}

export type CompareRequest = {
  "candidate"?: number;
  "k"?: number;
  "n_queries"?: number;
  "repeats"?: number;
  "seed"?: number;
  "left_nprobe"?: (number | null);
  "right_nprobe"?: (number | null);
  "left_ef_search"?: (number | null);
  "right_ef_search"?: (number | null);
}

export type CompareResultOut = {
  "metric": string;
  "k": number;
  "n_queries": number;
  "query_origin": "given" | "sampled";
  "query_sha256": string;
  "query_seed": (number | null);
  "repeats": number;
  "seed": number;
  "environment": Record<string, (string | number)>;
  "left": CompareMeasurementOut;
  "right": CompareMeasurementOut;
  "n_changed": number;
  "n_improved": number;
  "n_worsened": number;
  "changes": Array<QueryChangeOut>;
  "changes_truncated": boolean;
}

export type DemoLimitsOut = {
  "max_k": number;
  "max_ef_search": number;
  "max_sweep_queries": number;
  "max_sweep_values": number;
  "max_sweep_k": number;
  "umap_from_cache_only": boolean;
}

export type ErrorResponse = {
  "error_code": string;
  "message": string;
  "hint": (string | null);
}

export type EvaluationJobResponse = {
  "job_id": string;
  "status": "running" | "done" | "failed" | "cancelled";
  "progress": number;
  "message": string;
  "error": (string | null);
  "result": (EvaluationResultOut | null);
}

export type EvaluationRequest = {
  "judgements": string;
  "k"?: number;
  "candidates"?: (number | null);
  "nprobe"?: (number | null);
  "ef_search"?: (number | null);
}

export type EvaluationResultOut = {
  "k": number;
  "metric": string;
  "params": Record<string, number>;
  "n_queries": number;
  "ndcg_gain": string;
  "unjudged": string;
  "metrics": RelevanceMetricsOut;
  "reranked_metrics": (RelevanceMetricsOut | null);
  "candidates": (number | null);
  "queries": Array<EvaluationRowOut>;
}

export type EvaluationRowOut = {
  "row": number;
  "metrics": RelevanceMetricsOut;
  "latency_ms": number;
  "ids": Array<string>;
  "reranked_metrics": (RelevanceMetricsOut | null);
  "reranked_latency_ms": (number | null);
  "reranked_ids": (Array<string> | null);
}

export type EvidenceOut = {
  "label": string;
  "value": string;
}

export type HTTPValidationError = {
  "detail"?: Array<ValidationError>;
}

export type HealthResponse = {
  "status": "ok";
}

export type HistoryCompareRequest = {
  "baseline": string;
  "current": string;
}

export type HistoryComparison = {
  "comparable": boolean;
  "regressed": boolean;
  "notes": Array<string>;
  "points": Array<PointDeltaOut>;
}

export type HistoryRecord = {
  "id": string;
  "kind": string;
  "label": string;
  "index": string;
  "created_at": string;
  "data": Record<string, unknown>;
}

export type HistoryRename = {
  "label": string;
}

export type HistoryResponse = {
  "enabled": boolean;
  "warning": (string | null);
  "current_index": (string | null);
  "runs": Array<HistorySummary>;
}

export type HistorySummary = {
  "id": string;
  "kind": string;
  "label": string;
  "index": string;
  "created_at": string;
}

export type HnswGraphResponse = {
  "level": number;
  "n_level_nodes": number;
  "sampled": boolean;
  "ids": Array<(number | string)>;
  "x": Array<number>;
  "y": Array<number>;
  "top_levels": Array<number>;
  "edges_src": Array<number>;
  "edges_dst": Array<number>;
}

export type HnswLevelStats = {
  "level": number;
  "n_nodes": number;
  "max_links": number;
  "degree_mean": number;
  "degree_min": number;
  "degree_max": number;
  "degree_hist": Array<number>;
}

export type HnswLevelTrace = {
  "level": number;
  "entry": (number | string);
  "steps": Array<HnswStepOut>;
}

export type HnswStatsResponse = {
  "entry_point": (number | string);
  "max_level": number;
  "m": number;
  "ef_search": number;
  "ef_construction": number;
  "levels": Array<HnswLevelStats>;
}

export type HnswStepOut = {
  "expanded": (number | string);
  "expanded_distance": number;
  "visits": Array<HnswVisitOut>;
}

export type HnswTraceNeighbour = {
  "rank": number;
  "id": (number | string);
  "distance": number;
  "outcome": "FOUND" | "VISITED_NOT_KEPT" | "NOT_REACHED";
  "top_level": number;
  "snippet": (Record<string, string> | null);
}

export type HnswTraceNodes = {
  "ids": Array<(number | string)>;
  "x": Array<number>;
  "y": Array<number>;
  "top_levels": Array<number>;
}

export type HnswTraceResponse = {
  "metric": string;
  "higher_is_closer": boolean;
  "ef_search": number;
  "k": number;
  "entry_point": (number | string);
  "max_level": number;
  "levels": Array<HnswLevelTrace>;
  "results": Array<ResultRow>;
  "faiss_ids": Array<(number | string)>;
  "overlap_with_faiss": number;
  "truth": (Array<HnswTraceNeighbour> | null);
  "recall": (number | null);
  "nodes": HnswTraceNodes;
  "query_xy": (Array<number> | null);
}

export type HnswVisitOut = {
  "node": (number | string);
  "distance": number;
  "accepted": boolean;
}

export type InfoResponse = {
  "version": string;
  "name": string;
  "kind": string;
  "class_chain": Array<string>;
  "transforms": Array<TransformOut>;
  "d": number;
  "core_d": number;
  "ntotal": number;
  "metric": string;
  "higher_is_closer": boolean;
  "is_trained": boolean;
  "params": Record<string, (number | number | boolean | string)>;
  "has_id_map": boolean;
  "has_refine": boolean;
  "supported": boolean;
  "unsupported_reason": (string | null);
  "ground_truth_source": ("raw" | "reconstructed" | null);
  "max_points": number;
  "sweep": (SweepDefaults | null);
  "demo_limits": (DemoLimitsOut | null);
  "compare": Array<CompareCandidateOut>;
  "inputs": InputsOut;
  "memory": MemoryOut;
}

export type InputsOut = {
  "raw_vectors": boolean;
  "metadata_rows": (number | null);
  "metadata_columns": Array<string>;
  "metadata_coverage": (number | null);
  "embedder": (string | null);
  "embedder_status": ("loading" | "ready" | "failed" | null);
  "queries": (number | null);
}

export type IvfTraceResponse = {
  "nprobe": number;
  "nlist": number;
  "min_nprobe": number;
  "recall": (number | null);
  "metric": string;
  "higher_is_closer": boolean;
  "probes": Array<ProbeRow>;
  "neighbours": Array<TruthRow>;
}

export type JobStatusResponse = {
  "status": "running" | "done" | "failed" | "cancelled";
  "progress": number;
  "message": string;
  "error": (string | null);
}

export type ListMembersResponse = {
  "list_no": number;
  "size": number;
  "offset": number;
  "limit": number;
  "members": Array<MemberOut>;
}

export type ListSizesResponse = {
  "nlist": number;
  "sizes": Array<number>;
  "n_empty": number;
  "imbalance_factor": number;
  "min": number;
  "median": number;
  "max": number;
  "top_lists": Array<TopList>;
  "top_5pct_share": number;
}

export type MemberOut = {
  "id": (number | string);
  "snippet": (Record<string, string> | null);
}

export type MemoryOut = {
  "vectors_bytes": (number | null);
  "vectors_mapped": boolean;
  "mmap_note": (string | null);
  "reconstruct_bytes": number;
  "reconstructed": boolean;
  "pq_workspace_bytes": number;
}

export type MetadataResponse = {
  "id": (number | string);
  "row": Record<string, unknown>;
}

export type MissReason = "FOUND" | "CELL_NOT_PROBED" | "QUANTIZATION" | "TRANSFORM" | "RANKED_OUT"

export type PointDeltaOut = {
  "value": number;
  "baseline_recall": number;
  "recall": number;
  "recall_change": number;
  "baseline_p95_ms": number;
  "p95_ms": number;
  "p95_change": number;
  "recall_regressed": boolean;
  "latency_regressed": boolean;
}

export type PqDistortion = {
  "true": Array<number>;
  "approx": Array<number>;
  "near": Array<boolean>;
  "correlation": number;
  "near_correlation": number;
}

export type PqErrorResponse = {
  "available": boolean;
  "reason": (string | null);
  "hint": (string | null);
  "kind": (string | null);
  "metric": (string | null);
  "n": (number | null);
  "code_size": (number | null);
  "raw_bytes": (number | null);
  "has_transform": boolean;
  "mean": (number | null);
  "median": (number | null);
  "p95": (number | null);
  "max": (number | null);
  "relative_mean": (number | null);
  "histogram": (PqHistogram | null);
  "per_list": (Array<PqListError> | null);
  "worst": (Array<PqWorst> | null);
  "distortion": (PqDistortion | null);
}

export type PqHistogram = {
  "edges": Array<number>;
  "counts": Array<number>;
}

export type PqListError = {
  "list_no": number;
  "size": number;
  "mean_error": number;
}

export type PqWorst = {
  "id": (number | string);
  "error": number;
  "relative": number;
  "list_no": (number | null);
  "snippet": (Record<string, string> | null);
}

export type ProbeRow = {
  "probe_rank": number;
  "list_no": number;
  "centroid_distance": number;
  "probed": boolean;
  "size": number;
  "n_true_neighbours": number;
}

export type ProjectionRef = {
  "method"?: "pca" | "umap";
  "dims"?: 2 | 3;
}

export type ProjectionResponse = {
  "status": "done";
  "kind": "points" | "centroids";
  "method": "pca" | "umap";
  "dims": 2 | 3;
  "ids": Array<(number | string)>;
  "x": Array<number>;
  "y": Array<number>;
  "z": (Array<number> | null);
  "list_nos": (Array<number> | null);
  "n_total": number;
  "sampled": boolean;
  "explained_variance": (Array<number> | null);
  "cache_warning": (string | null);
}

export type QueryChangeOut = {
  "query_no": number;
  "id": (number | string | null);
  "left_recall": number;
  "right_recall": number;
  "left_only": Array<(number | string)>;
  "right_only": Array<(number | string)>;
  "overlap": number;
}

export type QueryIn = {
  "id"?: (number | string | null);
  "vector"?: (Array<number> | null);
  "text"?: (string | null);
  "row"?: (number | null);
}

export type RelevanceMetricsOut = {
  "recall": number;
  "mrr": number;
  "ndcg": number;
}

export type ResultRow = {
  "rank": number;
  "id": (number | string);
  "distance": number;
  "list_no": (number | null);
  "in_truth": (boolean | null);
  "snippet": (Record<string, string> | null);
}

export type RunDecisionOut = {
  "target_recall": number;
  "confident": boolean;
  "max_p95_ms": (number | null);
  "status": "ok" | "recall" | "latency";
  "recommended": (number | null);
}

export type RunIndexOut = {
  "sha1": string;
  "name": (string | null);
  "kind": string;
  "class_chain": Array<string>;
  "ntotal": number;
  "d": number;
  "metric": string;
  "params": Record<string, (number | number | boolean | string)>;
}

export type RunPointOut = {
  "value": number;
  "recall": number;
  "recall_ci_low": (number | null);
  "recall_ci_high": (number | null);
  "latency_mean_ms": number;
  "latency_p95_ms": number;
  "probe_coverage": (number | null);
  "recall_distribution": Array<[number, number]>;
  "worst_queries": Array<RunWorstQueryOut>;
}

export type RunQueriesOut = {
  "origin": "given" | "sampled";
  "n": number;
  "sha256": string;
  "seed": (number | null);
}

export type RunSettingsOut = {
  "param": "nprobe" | "efSearch";
  "values": Array<number>;
  "k": number;
  "repeats": number;
  "seed": number;
  "truth_source": "raw" | "reconstructed";
  "ground_truth_fingerprint": (string | null);
}

export type RunWorstQueryOut = {
  "query_no": number;
  "id": (number | string | null);
  "recall": number;
}

export type SearchRequest = {
  "query": QueryIn;
  "k"?: number;
  "nprobe"?: (number | null);
  "efSearch"?: (number | null);
  "compare"?: boolean;
  "candidates"?: (number | null);
  "trace"?: boolean;
  "projection"?: (ProjectionRef | null);
}

export type SearchResponse = {
  "query_kind": "id" | "vector" | "text" | "row";
  "metric": string;
  "higher_is_closer": boolean;
  "k": number;
  "params": Record<string, number>;
  "latency_ms": number;
  "results": Array<ResultRow>;
  "reranked": (Array<ResultRow> | null);
  "reranked_recall": (number | null);
  "reranked_latency_ms": (number | null);
  "candidate_count": (number | null);
  "truth": (Array<TruthRow> | null);
  "recall": (number | null);
  "truth_source": ("raw" | "reconstructed" | null);
  "min_nprobe": (number | null);
  "reason_counts": (Record<string, number> | null);
  "query_coords": (Array<number> | null);
  "ivf_trace": (IvfTraceResponse | null);
}

export type SuggestionOut = {
  "kind": "PROBE_MORE" | "RANKING_LIMIT" | "SEARCH_WIDER" | "RECALL_PLATEAU" | "FAILING_QUERIES" | "LIST_IMBALANCE" | "LATENCY_BUDGET";
  "title": string;
  "detail": string;
  "evidence": Array<EvidenceOut>;
  "sweep_values": (Array<number> | null);
  "view": ("overview" | "quantization" | "compare" | "query" | null);
  "query_id": (number | string | null);
  "at_value": (number | null);
}

export type SweepAdviceResponse = {
  "target_recall": number;
  "confident": boolean;
  "max_p95_ms": (number | null);
  "suggestions": Array<SuggestionOut>;
}

export type SweepDefaults = {
  "param": "nprobe" | "efSearch";
  "values": Array<number>;
  "max_value": (number | null);
}

export type SweepJobResponse = {
  "job_id": string;
  "status": "running" | "done" | "failed" | "cancelled";
  "progress": number;
  "message": string;
  "error": (string | null);
  "result": (SweepResultOut | null);
}

export type SweepPointOut = {
  "value": number;
  "recall": number;
  "latency_mean_ms": number;
  "latency_p95_ms": number;
  "recall_ci_low": (number | null);
  "recall_ci_high": (number | null);
  "recall_distribution": Array<[number, number]>;
  "worst_queries": Array<WorstQueryOut>;
  "probe_coverage": (number | null);
}

export type SweepRequest = {
  "param"?: ("nprobe" | "efSearch" | null);
  "values"?: (Array<number> | null);
  "k"?: number;
  "n_queries"?: number;
  "repeats"?: number;
  "seed"?: number;
}

export type SweepResultOut = {
  "param": "nprobe" | "efSearch";
  "k": number;
  "n_queries": number;
  "query_origin": "given" | "sampled";
  "truth_source": "raw" | "reconstructed";
  "points": Array<SweepPointOut>;
  "pareto_values": Array<number>;
  "repeats": number;
  "seed": number;
  "query_sha256": string;
  "environment": Record<string, (string | number)>;
  "query_seed": (number | null);
}

export type SweepRunOut = {
  "format": string;
  "version": number;
  "label": (string | null);
  "created_at": string;
  "faissight": string;
  "index": RunIndexOut;
  "queries": RunQueriesOut;
  "settings": RunSettingsOut;
  "environment": Record<string, (string | number)>;
  "decision": RunDecisionOut;
  "points": Array<RunPointOut>;
}

export type TopList = {
  "list_no": number;
  "size": number;
}

export type TransformOut = {
  "name": string;
  "d_in": number;
  "d_out": number;
}

export type TruthRow = {
  "rank": number;
  "id": (number | string);
  "distance": number;
  "list_no": (number | null);
  "probe_rank": (number | null);
  "reason": (MissReason | null);
  "found_rank": (number | null);
  "snippet": (Record<string, string> | null);
}

export type ValidationError = {
  "loc": Array<(string | number)>;
  "msg": string;
  "type": string;
  "input"?: unknown;
  "ctx"?: Record<string, unknown>;
}

export type WorstQueryOut = {
  "query_no": number;
  "id": (number | string | null);
  "recall": number;
  "probe_coverage": (number | null);
}
