"""Generate TypeScript schema types from the actual FastAPI OpenAPI document.

Run with --check in CI. No running server, FAISS index, or extra dependency required.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from fastapi import FastAPI

from faissight.server.routes import router
from faissight.server.schemas import ErrorResponse

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "frontend/src/api/schema.generated.ts"


def name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1].replace("-", "_")


def render(s: dict[str, Any]) -> str:
    if "$ref" in s:
        return name(s["$ref"])
    if "const" in s:
        return json.dumps(s["const"])
    if "enum" in s:
        return " | ".join(json.dumps(x) for x in s["enum"])
    for union, sep in [("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")]:
        if union in s:
            return "(" + sep.join(render(x) for x in s[union]) + ")"
    t = s.get("type")
    if t in ("number", "integer"):
        # UserId accepts strings as input and emits them for large int64 values.
        if s.get("maximum") == 2**63 - 1:
            return "(number | string)"
        return "number"
    if t in ("string", "boolean", "null"):
        return t
    if t == "array":
        if "prefixItems" in s:
            return "[" + ", ".join(render(x) for x in s["prefixItems"]) + "]"
        return f"Array<{render(s.get('items', {}))}>"
    if t == "object" or "properties" in s:
        if "properties" in s:
            required = s.get("required", [])
            props = [
                f"{json.dumps(k)}{'' if k in required else '?'}: {render(v)}"
                for k, v in s["properties"].items()
            ]
            return "{\n" + "\n".join("  " + p + ";" for p in props) + "\n}"
        extra = s.get("additionalProperties", {})
        return f"Record<string, {render(extra) if isinstance(extra, dict) else 'unknown'}>"
    if not s or set(s) <= {"title", "description", "default"}:
        return "unknown"
    raise ValueError(f"Unsupported JSON Schema: {s}")


def generate() -> str:
    app = FastAPI()
    app.include_router(router, prefix="/api")
    schemas = app.openapi()["components"]["schemas"]
    schemas["ErrorResponse"] = ErrorResponse.model_json_schema(mode="serialization")
    return (
        "// Generated by scripts/generate_api_types.py. Do not edit.\n\n"
        + "\n\n".join(
            f"export type {name(key)} = {render(schema)}" for key, schema in sorted(schemas.items())
        )
        + "\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not DEST.exists() or DEST.read_text() != content:
            raise SystemExit(
                "API types are stale. Run: uv run python scripts/generate_api_types.py"
            )
    else:
        DEST.write_text(content)
